#!/bin/bash
# set -eux
# ROOT="$(dirname `readlink -f $0`)"
# OLD_PWD=`pwd`
# MODULES="${ROOT}"/deployment_scripts/puppet/modules
# cd $MODULES
# # Download upstream puppet-calico
# COMMIT="421530d"
# OWNER="beddari"
# REPO="puppet-calico"
# curl -L "https://github.com/${OWNER}/${REPO}/tarball/${COMMIT}" | tar xzf -
# mv "${OWNER}-${REPO}-${COMMIT}" calico
# # Download upstream bird module
# COMMIT="869cf08"
# OWNER="norcams"
# REPO="puppet-bird"
# curl -L "https://github.com/${OWNER}/${REPO}/tarball/${COMMIT}" | tar xzf -
# mv "${OWNER}-${REPO}-${COMMIT}" bird
# ###
# cd $OLD_PWD
